### ISSUE TITLE
broken jailbreak  on 14.3

### ISSUE THREAD

**Issue by Szhann** [ProcursusTeam/libiosexec#16]
![image](https://user-images.githubusercontent.com/22450827/232967442-0e88e985-7891-452f-a0a8-f6827e0ef218.png)

**Comment by TheRealKeto** [comment]
This issue is being worked on as many others have reported it on our Discord server. Please be patient.

**Comment by zhooo-95** [comment]
v1.3.0

**Comment by Teutates** [comment]
This was a temporarily broken upload fixed in version 1.3.1. The broken install was removed.

To fix, if you have Filza, download https://apt.procurs.us/libiosexec.1.dylib and place it in /usr/lib
Make sure the permissions are set to 755 and everything will work.
In Filza, that’s:
Owner: Read Write Execute
Group: Read Execute
Others: Read Execute

**Comment by monsm** [comment]
@Teutates The phone's rebooted. Filza can't open it without the jailbreak. Any other ideas

**Comment by asdfugil** [comment]
filza will open when taurine says ERR_JAILBREAK
